trigger:
  branches:
    include:
      - main
  paths:
    include:
      - .pipelines/dev/deploy-sofware-eng-image-template.yaml
      - ./vmimages/softwareeng/**

variables:
  - group: tre-core-variables-dev
  - group: tre-core-auth-secrets-dev
  - group: azure-environment

pool:
  vmImage: ubuntu-latest

jobs:
  - template: /.pipelines/jobs/deploy-sofware-eng-image-template.yaml
    parameters:
      LOCK_ENV: "dev"
