trigger:
  branches:
    include:
      - main
  paths:
    include:
      - .pipelines/dev/prepare-software-eng-dependencies.yaml
      - ./vmimages/softwareeng/scripts/**

variables:
  - group: tre-core-variables-dev
  - group: tre-core-auth-secrets-dev
  - group: azure-environment

pool:
  vmImage: ubuntu-latest

jobs:
  - template: /.pipelines/jobs/prepare-software-eng-dependencies.yaml
    parameters:
      LOCK_ENV: "dev"
