{{- if .Values.gateway.enabled }}

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "tre.fullname" . }}-gateway
spec:
  gatewayClassName: {{ include "tre.fullname" . }}-gateway-class
  infrastructure:
    {{- if eq (lower .Values.gateway.type) "envoy" }}
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: {{ include "tre.fullname" . }}-envoy-proxy-config
    {{- end }}
  {{- if .Values.gateway.ipAddress }}
  addresses:
    - type: IPAddress
      value: {{ .Values.gateway.ipAddress | quote }}
  {{- end }}
  listeners:
  - name: tre-web
    hostname: {{ .Values.gateway.hostname | quote }}
    protocol: HTTPS
    port: {{ .Values.gateway.port | default 443 }}
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - group: ""
        kind: Secret
        name: {{ include "tre.fullname" $ }}-tls

{{- end }}
