trigger:
  branches:
    include:
      - main
  paths:
    include:
      - .pipelines/dev/workspace-services/build-publish-register-workspace-service-azuredevops-project.yaml
      - ./templates/workspace_services/azuredevops_project/**
pool:
  vmImage: ubuntu-latest

variables:
  - group: tre-core-variables-dev
  - group: tre-core-auth-secrets-dev
  - group: azure-environment

jobs:
  - template: /.pipelines/jobs/build-publish-register-workspace-service-bundle.yaml
    parameters:
      WORKSPACE_SERVICE_BUNDLE: "azuredevops_project"
      LOCK_ENV: "dev"
