trigger: none

variables:
  - group: tre-core-variables-prod
  - group: tre-core-auth-secrets-prod
  - group: azure-environment

pool:
  vmImage: ubuntu-latest

jobs:
  - template: /.pipelines/jobs/prepare-software-eng-dependencies.yaml
    parameters:
      LOCK_ENV: "prod"
