{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tre.serviceAccountName" . }}
  labels:
    {{- include "tre.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/tenant-id: {{ .Values.serviceAccount.tenantId }}
    azure.workload.identity/client-id: {{ .Values.serviceAccount.clientId }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
