trigger:
  branches:
    include:
      - main
  paths:
    include:
      - .pipelines/dev/build-api-image.yaml
      - ./api_app/**

variables:
  - group: tre-core-variables-dev
  - group: tre-core-auth-secrets-dev
  - group: azure-environment

pool:
  vmImage: ubuntu-latest

jobs:
  - template: /.pipelines/jobs/build-api-image.yaml
    parameters:
      LOCK_ENV: "dev"
