apiVersion: v1
kind: Service
metadata:
  name: {{ include "tre.fullname" . }}-ui
  labels:
    {{- include "tre.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    component: ui
    {{- include "tre.selectorLabels" . | nindent 4 }}
