trigger:
  branches:
    include:
      - main
variables:
  - group: tre-core-variables-dev
  - group: tre-core-auth-secrets-dev
  - group: azure-environment

pool:
  vmImage: ubuntu-latest

jobs:
  - template: /.pipelines/jobs/build-publish-register-user-resource-bundle.yaml
    parameters:
      WORKSPACE_SERVICE: guacamole
      USER_RESOURCE_BUNDLE: guacamole-azure-import-reviewvm
      LOCK_ENV: "dev"
